### ISSUE TITLE
What is the suggested course of action if the password of a site gets compromised?

### ISSUE THREAD

**Issue by MrGreenTea** [elfenware/obliviate#17]
This looks like a very interesting approach to password management. Thanks you for your work!

I have a few questions I would like to hear your opinion on.
- How does this differ from using the same password on all sites? (for example the cipher key)
- What should a user do if for example their password for github.com is compromised?

**Comment by dar5hak** [comment]
@MrGreenTea Thanks for trying it out, and those are really good questions. I should probably put them in an FAQ section.

> How does this differ from using the same password on all sites? (for example the cipher key)

The password is a function of the site name and the cipher key, so you get a different password for each site without having to remember multiple cipher keys. The way it is safer than having the same password is that if one gets compromised, it can't be used by malicious entities on other sites.

Your cipher key itself is unlikely to get compromised, because it is not stored anywhere except your own brain. So, you can safely pick one cipher key and use it as a master password for all sites.

> What should a user do if for example their password for github.com is compromised?

In that case, the best solution would be to slightly change one of the inputs: preferably the site input, like "github2".

I understand that this is one more thing to remember, but this only happens once in a while, so I hope it is not too inconvenient.

**Comment by dar5hak** [comment]
Closing this assuming I was able to answer your questions. Feel free to reopen if something is unclear.

**Comment by bender0791** [comment]
This is a very good answer, and it does make sense. However, the premise of this workflow, unless I'm mistaken, is that you should only have one password for a specific site, period. If you are ever forced to change your password, your cypher changes. When then happens (not if), you'll be switching to KeePassXC or equivalent for your "cypher" storage for different websites.

It is very intriguing project but the functional scope is very limiting. If you're forced to change password often, want or must enable 2FA via authenticator app or something else this isn't an option at all.

I do like the simplicity of it, but I do hope you address these scenarios via a FAQ before many people start relying on this and having to look elsewhere quickly soon after.

**Comment by dar5hak** [comment]
@bender0791 Thanks, that is a valid point, and I should put it in the [FAQ](https://github.com/elfenware/obliviate/wiki/Help-and-FAQ). I don't have a solution for this scenario, but the least I can do is clarify the tradeoff.
