### ISSUE TITLE
Enhancement: Allow for local key for extra protection.

### ISSUE THREAD

**Issue by Andremoda** [elfenware/obliviate#18]
Hello!

love the idea behind this application.

my only concern is, since there is a web application available, it'd be possible for people to brute force using obliviate.app.

one solution for this would be to allow users to also generate a private key file, save it locally, and use that as well in the generation algorithm. this would protect their passwords from being brute forced via the web.

**Comment by dar5hak** [comment]
Interesting. I'm somewhat reluctant to add a third input, but if it is needed for security, I'll do it.

And to make that decision, I need to understand the scenario better: let's say someone brute-forces the web app. What they would gain is a bunch of possible passwords. But how would they filter those to find the correct one?

(Forgive my ignorance; I'm no expert in cryptography.)

**Comment by Andremoda** [comment]
Hmm perhaps you are right. Since they don’t have the usernames it isn’t too useful. The only time I can see this being brute forcable is for targeted attacks (the attacker knows your username). They would also have to know about this tool and know that you use it. at which point they are probably just brute forcing your password outright. 

one thing that might make this more secure though , is setting a rate limit or something on how many passwords you can guess with your “nickname”.

in any case, I love the app :-) I am hesitant to covert to it fully yet because of one thing, I can never remember what I called each site LOL. 

But I think with a little memory training I could, and it’d be secure because it leaves no trace. 

awesome idea :-)

**Comment by dar5hak** [comment]
Setting a rate limit won't stop anyone from brute-forcing either, because they could just change the source code and run a modified version locally, or just exploit the PBKDF2 algorithm in their own script.

That said, even with a known username and an unknown cipher key, all they would get is a bunch of possible passwords, about the correctness of which they cannot make an educated guess, because they're gibberish.

As for protecting the cipher key itself from brute force attacks (e.g. when one of your passwords got leaked) you can make it long and “complex” by adding practically any Unicode character into them.

This, I assume, disarms the brute force algorithm, which is not prepared for permutations of all Unicode characters.

**Comment by dar5hak** [comment]
And one way to remember the site name is to just copy and paste its domain. Like `github.com`.

**Comment by dar5hak** [comment]
And many thanks for starting this discussion. Some of these are brilliant points that I should put into an FAQ section.

**Comment by dar5hak** [comment]
I have added the answers to this and a few other questions at https://github.com/elfenware/obliviate/wiki/Help-and-FAQ.

Closing this, but feel free to reopen if you want to discuss further.
